export const APP_SHOW_LOADING = "APP_SHOW_LOADING";
export const APP_HIDE_LOADING = "APP_HIDE_LOADING";

export const LOGIN_DO_FORGOT_PASS = "LOGIN_DO_FORGOT_PASS";
export const LOGIN_DO_LOGIN = "LOGIN_DO_LOGIN";
export const LOGIN_CHECKED = "LOGIN_CHECKED";